-- vim.cmd([[hi FloatBorder guifg=#515151  guibg=NONE]])
--
-- require("noice").setup({
--   background_colour = "#000000",
-- 	lsp = {
-- 		-- override markdown rendering so that **cmp** and other plugins use **Treesitter**
-- 		override = {
-- 			["vim.lsp.util.convert_input_to_markdown_lines"] = true,
-- 			["vim.lsp.util.stylize_markdown"] = true,
-- 			["cmp.entry.get_documentation"] = true,
-- 		},
-- 	},
-- 	-- you can enable a preset for easier configuration
-- 	presets = {
-- 		bottom_search = true, -- use a classic bottom cmdline for search
-- 		command_palette = true, -- position the cmdline and popupmenu together
-- 		long_message_to_split = true, -- long messages will be sent to a split
-- 		inc_rename = false, -- enables an input dialog for inc-rename.nvim
-- 		-- lsp_doc_border = true, -- add a border to hover docs and signature help
-- 		scrollbar = false,
-- 	},
-- 	{
-- 		win_options = {
-- 			winhighlight = {
-- 				Normal = "NormalFloat",
-- 				FloatBorder = "FloatBorder",
-- 			},
-- 		},
-- 	},
-- })
--
--
-- vim.cmd([[hi FloatBorder guifg=#515151  guibg=NONE]])
