require("nvim-treesitter.configs").setup({
	highlight = {
		enable = true,
    additional_vim_regex_highlighting=false,
	},
	rainbow = {
		enable = true,
		extended_mode = true,
		max_file_lines = nil,
	},
	indent = { enable = false, disable = { "rust" } },
	autotag = { enable = true },
	ensure_installed = {
		"json",
		"javascript",
		"typescript",
		"tsx",
		"yaml",
		"html",
		"css",
		"markdown",
		"markdown_inline",
		"svelte",
		"graphql",
		"bash",
		"lua",
		"vim",
		"dockerfile",
		"gitignore",
		"rust",
		"latex",
		"sql",
	},
	auto_install = true,
})
